//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.07.20 at 10:40:55 AM CEST
//

package groove.io.conceptual.configuration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="typeModel" type="{ConfigSchema}typeModel"/>
 *         &lt;element name="instanceModel" type="{ConfigSchema}instanceModel"/>
 *         &lt;element name="global" type="{ConfigSchema}global"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"typeModel", "instanceModel", "global"})
@XmlRootElement(name = "configuration")
@SuppressWarnings("javadoc")
public class Configuration {

    @XmlElement(required = true) protected TypeModel typeModel;
    @XmlElement(required = true) protected InstanceModel instanceModel;
    @XmlElement(required = true) protected Global global;

    /**
     * Gets the value of the typeModel property.
     *
     * @return
     *     possible object is
     *     {@link TypeModel }
     *
     */
    public TypeModel getTypeModel() {
        return this.typeModel;
    }

    /**
     * Sets the value of the typeModel property.
     *
     * @param value
     *     allowed object is
     *     {@link TypeModel }
     *
     */
    public void setTypeModel(TypeModel value) {
        this.typeModel = value;
    }

    /**
     * Gets the value of the instanceModel property.
     *
     * @return
     *     possible object is
     *     {@link InstanceModel }
     *
     */
    public InstanceModel getInstanceModel() {
        return this.instanceModel;
    }

    /**
     * Sets the value of the instanceModel property.
     *
     * @param value
     *     allowed object is
     *     {@link InstanceModel }
     *
     */
    public void setInstanceModel(InstanceModel value) {
        this.instanceModel = value;
    }

    /**
     * Gets the value of the global property.
     *
     * @return
     *     possible object is
     *     {@link Global }
     *
     */
    public Global getGlobal() {
        return this.global;
    }

    /**
     * Sets the value of the global property.
     *
     * @param value
     *     allowed object is
     *     {@link Global }
     *
     */
    public void setGlobal(Global value) {
        this.global = value;
    }

}
