//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.07.20 at 10:40:55 AM CEST
//

package groove.io.conceptual.configuration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for instanceModel complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="instanceModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objects">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="use_identifier" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "instanceModel", propOrder = {"objects"})
@SuppressWarnings("javadoc")
public class InstanceModel {

    @XmlElement(required = true) protected InstanceModel.Objects objects;

    /**
     * Gets the value of the objects property.
     *
     * @return
     *     possible object is
     *     {@link InstanceModel.Objects }
     *
     */
    public InstanceModel.Objects getObjects() {
        return this.objects;
    }

    /**
     * Sets the value of the objects property.
     *
     * @param value
     *     allowed object is
     *     {@link InstanceModel.Objects }
     *
     */
    public void setObjects(InstanceModel.Objects value) {
        this.objects = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="use_identifier" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Objects {

        @XmlAttribute(name = "use_identifier") protected Boolean useIdentifier;

        /**
         * Gets the value of the useIdentifier property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        public boolean isUseIdentifier() {
            if (this.useIdentifier == null) {
                return true;
            } else {
                return this.useIdentifier;
            }
        }

        /**
         * Sets the value of the useIdentifier property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setUseIdentifier(Boolean value) {
            this.useIdentifier = value;
        }

    }

}
