//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.20 at 10:40:55 AM CEST 
//

package groove.io.conceptual.configuration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for stringsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stringsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dataPostfix" type="{http://www.w3.org/2001/XMLSchema}string" default="$data$" />
 *       &lt;attribute name="properPostfix" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="nullablePostfix" type="{http://www.w3.org/2001/XMLSchema}string" default="$nullable$" />
 *       &lt;attribute name="enumPostfix" type="{http://www.w3.org/2001/XMLSchema}string" default="$enum$" />
 *       &lt;attribute name="tuplePostfix" type="{http://www.w3.org/2001/XMLSchema}string" default="$tuple$" />
 *       &lt;attribute name="valueEdge" type="{http://www.w3.org/2001/XMLSchema}string" default="val" />
 *       &lt;attribute name="indexEdge" type="{http://www.w3.org/2001/XMLSchema}string" default="index" />
 *       &lt;attribute name="nextEdge" type="{http://www.w3.org/2001/XMLSchema}string" default="next" />
 *       &lt;attribute name="prevEdge" type="{http://www.w3.org/2001/XMLSchema}string" default="prev" />
 *       &lt;attribute name="oppositeEdge" type="{http://www.w3.org/2001/XMLSchema}string" default="opposite" />
 *       &lt;attribute name="dataValue" type="{http://www.w3.org/2001/XMLSchema}string" default="value" />
 *       &lt;attribute name="intermediatePostfix" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="nilName" type="{http://www.w3.org/2001/XMLSchema}string" default="Nil" />
 *       &lt;attribute name="intermediateName" type="{http://www.w3.org/2001/XMLSchema}string" default="elem" />
 *       &lt;attribute name="metaType" type="{http://www.w3.org/2001/XMLSchema}string" default="Type" />
 *       &lt;attribute name="metaClass" type="{http://www.w3.org/2001/XMLSchema}string" default="Class" />
 *       &lt;attribute name="metaClassNullable" type="{http://www.w3.org/2001/XMLSchema}string" default="NullableClass" />
 *       &lt;attribute name="metaEnum" type="{http://www.w3.org/2001/XMLSchema}string" default="Enum" />
 *       &lt;attribute name="metaTuple" type="{http://www.w3.org/2001/XMLSchema}string" default="Tuple" />
 *       &lt;attribute name="metaContainerBag" type="{http://www.w3.org/2001/XMLSchema}string" default="Bag" />
 *       &lt;attribute name="metaContainerSet" type="{http://www.w3.org/2001/XMLSchema}string" default="Set" />
 *       &lt;attribute name="metaContainerSeq" type="{http://www.w3.org/2001/XMLSchema}string" default="Seq" />
 *       &lt;attribute name="metaContainerOrd" type="{http://www.w3.org/2001/XMLSchema}string" default="Ord" />
 *       &lt;attribute name="metaDataType" type="{http://www.w3.org/2001/XMLSchema}string" default="DataType" />
 *       &lt;attribute name="metaIntermediate" type="{http://www.w3.org/2001/XMLSchema}string" default="Intermediate" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stringsType")
@SuppressWarnings("javadoc")
public class StringsType {
    @XmlAttribute(name = "dataPostfix")
    protected String dataPostfix;
    @XmlAttribute(name = "properPostfix")
    protected String properPostfix;
    @XmlAttribute(name = "nullablePostfix")
    protected String nullablePostfix;
    @XmlAttribute(name = "enumPostfix")
    protected String enumPostfix;
    @XmlAttribute(name = "tuplePostfix")
    protected String tuplePostfix;
    @XmlAttribute(name = "valueEdge")
    protected String valueEdge;
    @XmlAttribute(name = "indexEdge")
    protected String indexEdge;
    @XmlAttribute(name = "nextEdge")
    protected String nextEdge;
    @XmlAttribute(name = "prevEdge")
    protected String prevEdge;
    @XmlAttribute(name = "oppositeEdge")
    protected String oppositeEdge;
    @XmlAttribute(name = "dataValue")
    protected String dataValue;
    @XmlAttribute(name = "intermediatePostfix")
    protected String intermediatePostfix;
    @XmlAttribute(name = "nilName")
    protected String nilName;
    @XmlAttribute(name = "intermediateName")
    protected String intermediateName;
    @XmlAttribute(name = "metaType")
    protected String metaType;
    @XmlAttribute(name = "metaClass")
    protected String metaClass;
    @XmlAttribute(name = "metaClassNullable")
    protected String metaClassNullable;
    @XmlAttribute(name = "metaEnum")
    protected String metaEnum;
    @XmlAttribute(name = "metaTuple")
    protected String metaTuple;
    @XmlAttribute(name = "metaContainerBag")
    protected String metaContainerBag;
    @XmlAttribute(name = "metaContainerSet")
    protected String metaContainerSet;
    @XmlAttribute(name = "metaContainerSeq")
    protected String metaContainerSeq;
    @XmlAttribute(name = "metaContainerOrd")
    protected String metaContainerOrd;
    @XmlAttribute(name = "metaDataType")
    protected String metaDataType;
    @XmlAttribute(name = "metaIntermediate")
    protected String metaIntermediate;

    /**
     * Gets the value of the dataPostfix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataPostfix() {
        if (this.dataPostfix == null) {
            return "$data$";
        } else {
            return this.dataPostfix;
        }
    }

    /**
     * Sets the value of the dataPostfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataPostfix(String value) {
        this.dataPostfix = value;
    }

    /**
     * Gets the value of the properPostfix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProperPostfix() {
        if (this.properPostfix == null) {
            return "";
        } else {
            return this.properPostfix;
        }
    }

    /**
     * Sets the value of the properPostfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProperPostfix(String value) {
        this.properPostfix = value;
    }

    /**
     * Gets the value of the nullablePostfix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNullablePostfix() {
        if (this.nullablePostfix == null) {
            return "$nullable$";
        } else {
            return this.nullablePostfix;
        }
    }

    /**
     * Sets the value of the nullablePostfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNullablePostfix(String value) {
        this.nullablePostfix = value;
    }

    /**
     * Gets the value of the enumPostfix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnumPostfix() {
        if (this.enumPostfix == null) {
            return "$enum$";
        } else {
            return this.enumPostfix;
        }
    }

    /**
     * Sets the value of the enumPostfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnumPostfix(String value) {
        this.enumPostfix = value;
    }

    /**
     * Gets the value of the tuplePostfix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTuplePostfix() {
        if (this.tuplePostfix == null) {
            return "$tuple$";
        } else {
            return this.tuplePostfix;
        }
    }

    /**
     * Sets the value of the tuplePostfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTuplePostfix(String value) {
        this.tuplePostfix = value;
    }

    /**
     * Gets the value of the valueEdge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueEdge() {
        if (this.valueEdge == null) {
            return "val";
        } else {
            return this.valueEdge;
        }
    }

    /**
     * Sets the value of the valueEdge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueEdge(String value) {
        this.valueEdge = value;
    }

    /**
     * Gets the value of the indexEdge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexEdge() {
        if (this.indexEdge == null) {
            return "index";
        } else {
            return this.indexEdge;
        }
    }

    /**
     * Sets the value of the indexEdge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexEdge(String value) {
        this.indexEdge = value;
    }

    /**
     * Gets the value of the nextEdge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextEdge() {
        if (this.nextEdge == null) {
            return "next";
        } else {
            return this.nextEdge;
        }
    }

    /**
     * Sets the value of the nextEdge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextEdge(String value) {
        this.nextEdge = value;
    }

    /**
     * Gets the value of the prevEdge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevEdge() {
        if (this.prevEdge == null) {
            return "prev";
        } else {
            return this.prevEdge;
        }
    }

    /**
     * Sets the value of the prevEdge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevEdge(String value) {
        this.prevEdge = value;
    }

    /**
     * Gets the value of the oppositeEdge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOppositeEdge() {
        if (this.oppositeEdge == null) {
            return "opposite";
        } else {
            return this.oppositeEdge;
        }
    }

    /**
     * Sets the value of the oppositeEdge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOppositeEdge(String value) {
        this.oppositeEdge = value;
    }

    /**
     * Gets the value of the dataValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataValue() {
        if (this.dataValue == null) {
            return "value";
        } else {
            return this.dataValue;
        }
    }

    /**
     * Sets the value of the dataValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataValue(String value) {
        this.dataValue = value;
    }

    /**
     * Gets the value of the intermediatePostfix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermediatePostfix() {
        if (this.intermediatePostfix == null) {
            return "";
        } else {
            return this.intermediatePostfix;
        }
    }

    /**
     * Sets the value of the intermediatePostfix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermediatePostfix(String value) {
        this.intermediatePostfix = value;
    }

    /**
     * Gets the value of the nilName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNilName() {
        if (this.nilName == null) {
            return "Nil";
        } else {
            return this.nilName;
        }
    }

    /**
     * Sets the value of the nilName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNilName(String value) {
        this.nilName = value;
    }

    /**
     * Gets the value of the intermediateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermediateName() {
        if (this.intermediateName == null) {
            return "elem";
        } else {
            return this.intermediateName;
        }
    }

    /**
     * Sets the value of the intermediateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermediateName(String value) {
        this.intermediateName = value;
    }

    /**
     * Gets the value of the metaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaType() {
        if (this.metaType == null) {
            return "Type";
        } else {
            return this.metaType;
        }
    }

    /**
     * Sets the value of the metaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaType(String value) {
        this.metaType = value;
    }

    /**
     * Gets the value of the metaClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaClass() {
        if (this.metaClass == null) {
            return "Class";
        } else {
            return this.metaClass;
        }
    }

    /**
     * Sets the value of the metaClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaClass(String value) {
        this.metaClass = value;
    }

    /**
     * Gets the value of the metaClassNullable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaClassNullable() {
        if (this.metaClassNullable == null) {
            return "NullableClass";
        } else {
            return this.metaClassNullable;
        }
    }

    /**
     * Sets the value of the metaClassNullable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaClassNullable(String value) {
        this.metaClassNullable = value;
    }

    /**
     * Gets the value of the metaEnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaEnum() {
        if (this.metaEnum == null) {
            return "Enum";
        } else {
            return this.metaEnum;
        }
    }

    /**
     * Sets the value of the metaEnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaEnum(String value) {
        this.metaEnum = value;
    }

    /**
     * Gets the value of the metaTuple property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaTuple() {
        if (this.metaTuple == null) {
            return "Tuple";
        } else {
            return this.metaTuple;
        }
    }

    /**
     * Sets the value of the metaTuple property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaTuple(String value) {
        this.metaTuple = value;
    }

    /**
     * Gets the value of the metaContainerBag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaContainerBag() {
        if (this.metaContainerBag == null) {
            return "Bag";
        } else {
            return this.metaContainerBag;
        }
    }

    /**
     * Sets the value of the metaContainerBag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaContainerBag(String value) {
        this.metaContainerBag = value;
    }

    /**
     * Gets the value of the metaContainerSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaContainerSet() {
        if (this.metaContainerSet == null) {
            return "Set";
        } else {
            return this.metaContainerSet;
        }
    }

    /**
     * Sets the value of the metaContainerSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaContainerSet(String value) {
        this.metaContainerSet = value;
    }

    /**
     * Gets the value of the metaContainerSeq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaContainerSeq() {
        if (this.metaContainerSeq == null) {
            return "Seq";
        } else {
            return this.metaContainerSeq;
        }
    }

    /**
     * Sets the value of the metaContainerSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaContainerSeq(String value) {
        this.metaContainerSeq = value;
    }

    /**
     * Gets the value of the metaContainerOrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaContainerOrd() {
        if (this.metaContainerOrd == null) {
            return "Ord";
        } else {
            return this.metaContainerOrd;
        }
    }

    /**
     * Sets the value of the metaContainerOrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaContainerOrd(String value) {
        this.metaContainerOrd = value;
    }

    /**
     * Gets the value of the metaDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaDataType() {
        if (this.metaDataType == null) {
            return "DataType";
        } else {
            return this.metaDataType;
        }
    }

    /**
     * Sets the value of the metaDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaDataType(String value) {
        this.metaDataType = value;
    }

    /**
     * Gets the value of the metaIntermediate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaIntermediate() {
        if (this.metaIntermediate == null) {
            return "Intermediate";
        } else {
            return this.metaIntermediate;
        }
    }

    /**
     * Sets the value of the metaIntermediate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaIntermediate(String value) {
        this.metaIntermediate = value;
    }

}
